var data = [
  {
    "line_number": 2,
    "Incident_ID": 1290435,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Nebraska",
    "City_Or_County": " Omaha",
    "Address": " 2500 block of Emmet St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 3,
    "Incident_ID": 1291253,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " West Virginia",
    "City_Or_County": " Worthington",
    "Address": " Michael Hill Rd",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 4,
    "Incident_ID": 1289028,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Oklahoma",
    "City_Or_County": " Oklahoma City",
    "Address": " N Rockwell Ave and W Wilshire Blvd",
    "Number_Killed": 0,
    "Number_Injured": 1,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 5,
    "Incident_ID": 1290413,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Nevada",
    "City_Or_County": " Las Vegas",
    "Address": " N E St and Jefferson Ave",
    "Number_Killed": 0,
    "Number_Injured": 1,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 6,
    "Incident_ID": 1290400,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Vermont",
    "City_Or_County": " Burlington",
    "Address": " N Champlain St and Manhattan Dr",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 7,
    "Incident_ID": 1295009,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Missouri",
    "City_Or_County": " Saint Louis (Overland)",
    "Address": " N/A",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 8,
    "Incident_ID": 1291926,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " North Carolina",
    "City_Or_County": " Durham",
    "Address": " Hill St",
    "Number_Killed": 0,
    "Number_Injured": 1,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 9,
    "Incident_ID": 1290378,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Massachusetts",
    "City_Or_County": " Worcester",
    "Address": " Dorchester St and Cutler St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 10,
    "Incident_ID": 1290368,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Texas",
    "City_Or_County": " Houston",
    "Address": " Kashmere St and Collingsworth St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 11,
    "Incident_ID": 1290364,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Massachusetts",
    "City_Or_County": " Boston",
    "Address": " Harrison Ave and Oxford Pl",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 12,
    "Incident_ID": 1289364,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Indiana",
    "City_Or_County": " Evansville",
    "Address": " West Columbia St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 13,
    "Incident_ID": 1289362,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " New York",
    "City_Or_County": " New York (Manhattan)",
    "Address": " 110 Bedford St",
    "Number_Killed": 1,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 14,
    "Incident_ID": 1292848,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Kansas",
    "City_Or_County": " Olathe",
    "Address": " 12051 Bass Pro Dr",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 15,
    "Incident_ID": 1289794,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Georgia",
    "City_Or_County": " Stone Mountain",
    "Address": " 5345 Memorial Dr",
    "Number_Killed": 1,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 16,
    "Incident_ID": 1291834,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Florida",
    "City_Or_County": " Fort Pierce",
    "Address": " 2400 block of N 42nd St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 17,
    "Incident_ID": 1290146,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Texas",
    "City_Or_County": " Fort Worth",
    "Address": " 5430 Miller Ave",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 18,
    "Incident_ID": 1290313,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Kansas",
    "City_Or_County": " Goessel",
    "Address": " 301 E Commercial St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 19,
    "Incident_ID": 1288927,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Colorado",
    "City_Or_County": " Longmont",
    "Address": " 2211 Pratt St",
    "Number_Killed": 1,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 20,
    "Incident_ID": 1291156,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Texas",
    "City_Or_County": " Mexia",
    "Address": " 500 block of W Commerce St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 21,
    "Incident_ID": 1290298,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Ohio",
    "City_Or_County": " Dayton",
    "Address": " 2500 block of Home Ave",
    "Number_Killed": 0,
    "Number_Injured": 1,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 22,
    "Incident_ID": 1289318,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Massachusetts",
    "City_Or_County": " Methuen",
    "Address": " Lowell St and N Lowell St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 23,
    "Incident_ID": 1290261,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Kentucky",
    "City_Or_County": " Owensboro",
    "Address": " 700 block of Elm St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 24,
    "Incident_ID": 1290285,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Texas",
    "City_Or_County": " Houston",
    "Address": " 12101 Fondren Rd",
    "Number_Killed": 1,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 25,
    "Incident_ID": 1290274,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Kansas",
    "City_Or_County": " Topeka",
    "Address": " SW 17th St and SW Westport Dr",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 26,
    "Incident_ID": 1290266,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Louisiana",
    "City_Or_County": " Baton Rouge",
    "Address": " 6300 block of Airline Hwy",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 28,
    "Incident_ID": 1290435,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Nebraska",
    "City_Or_County": " Omaha",
    "Address": " 2500 block of Emmet St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 29,
    "Incident_ID": 1291253,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " West Virginia",
    "City_Or_County": " Worthington",
    "Address": " Michael Hill Rd",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 30,
    "Incident_ID": 1289028,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Oklahoma",
    "City_Or_County": " Oklahoma City",
    "Address": " N Rockwell Ave and W Wilshire Blvd",
    "Number_Killed": 0,
    "Number_Injured": 1,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 31,
    "Incident_ID": 1290413,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Nevada",
    "City_Or_County": " Las Vegas",
    "Address": " N E St and Jefferson Ave",
    "Number_Killed": 0,
    "Number_Injured": 1,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 32,
    "Incident_ID": 1290400,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Vermont",
    "City_Or_County": " Burlington",
    "Address": " N Champlain St and Manhattan Dr",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 33,
    "Incident_ID": 1295009,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Missouri",
    "City_Or_County": " Saint Louis (Overland)",
    "Address": " N/A",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 34,
    "Incident_ID": 1291926,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " North Carolina",
    "City_Or_County": " Durham",
    "Address": " Hill St",
    "Number_Killed": 0,
    "Number_Injured": 1,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 35,
    "Incident_ID": 1290378,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Massachusetts",
    "City_Or_County": " Worcester",
    "Address": " Dorchester St and Cutler St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 36,
    "Incident_ID": 1290368,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Texas",
    "City_Or_County": " Houston",
    "Address": " Kashmere St and Collingsworth St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 37,
    "Incident_ID": 1290364,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Massachusetts",
    "City_Or_County": " Boston",
    "Address": " Harrison Ave and Oxford Pl",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 38,
    "Incident_ID": 1289364,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Indiana",
    "City_Or_County": " Evansville",
    "Address": " West Columbia St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 39,
    "Incident_ID": 1289362,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " New York",
    "City_Or_County": " New York (Manhattan)",
    "Address": " 110 Bedford St",
    "Number_Killed": 1,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 40,
    "Incident_ID": 1292848,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Kansas",
    "City_Or_County": " Olathe",
    "Address": " 12051 Bass Pro Dr",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 41,
    "Incident_ID": 1289794,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Georgia",
    "City_Or_County": " Stone Mountain",
    "Address": " 5345 Memorial Dr",
    "Number_Killed": 1,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 42,
    "Incident_ID": 1291834,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Florida",
    "City_Or_County": " Fort Pierce",
    "Address": " 2400 block of N 42nd St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 43,
    "Incident_ID": 1290146,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Texas",
    "City_Or_County": " Fort Worth",
    "Address": " 5430 Miller Ave",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 44,
    "Incident_ID": 1290313,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Kansas",
    "City_Or_County": " Goessel",
    "Address": " 301 E Commercial St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 45,
    "Incident_ID": 1288927,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Colorado",
    "City_Or_County": " Longmont",
    "Address": " 2211 Pratt St",
    "Number_Killed": 1,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 46,
    "Incident_ID": 1291156,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Texas",
    "City_Or_County": " Mexia",
    "Address": " 500 block of W Commerce St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 47,
    "Incident_ID": 1290298,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Ohio",
    "City_Or_County": " Dayton",
    "Address": " 2500 block of Home Ave",
    "Number_Killed": 0,
    "Number_Injured": 1,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 48,
    "Incident_ID": 1289318,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Massachusetts",
    "City_Or_County": " Methuen",
    "Address": " Lowell St and N Lowell St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 49,
    "Incident_ID": 1290261,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Kentucky",
    "City_Or_County": " Owensboro",
    "Address": " 700 block of Elm St",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 50,
    "Incident_ID": 1290285,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Texas",
    "City_Or_County": " Houston",
    "Address": " 12101 Fondren Rd",
    "Number_Killed": 1,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 51,
    "Incident_ID": 1290274,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Kansas",
    "City_Or_County": " Topeka",
    "Address": " SW 17th St and SW Westport Dr",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  },
  {
    "line_number": 52,
    "Incident_ID": 1290266,
    "Incident_Date": " December 31",
    "year": 2018,
    "State": " Louisiana",
    "City_Or_County": " Baton Rouge",
    "Address": " 6300 block of Airline Hwy",
    "Number_Killed": 0,
    "Number_Injured": 0,
    "Operations": " View Incident\nView Source"
  }
 ]